
export const data = [
    {
      info: {
        id: "558083",
        name: "Geetham Veg restaurant",
        cloudinaryImageId: "t8o1vgx93ztwz8qcmg7r",
        locality: "Rajiv Gandhi Salai Navalur",
        areaName: "OMR Navalur",
        costForTwo: "₹250 for two",
        cuisines: ["South Indian", "Sweets"],
        avgRating: 4.5,
        veg: true,
        parentId: "335557",
        avgRatingString: "4.5",
        totalRatingsString: "10K+",
        promoted: true,
        adTrackingId:
          "cid=12903293~p=0~adgrpid=12903293#ag1~mp=SWIGGY_IN~bl=FOOD~aet=RESTAURANT~aeid=558083~eid=18ecdb06-8fa1-40d9-b57c-4512f8fcbda1~srvts=1713945467570~collid=83646",
        sla: {
          deliveryTime: 42,
          lastMileTravel: 6.2,
          serviceability: "SERVICEABLE",
          slaString: "40-45 mins",
          lastMileTravelString: "6.2 km",
          iconType: "ICON_TYPE_EMPTY",
        },
      },
    },
    {
      info: {
        id: "690702",
        name: "Pizza Hut",
        cloudinaryImageId: "2b4f62d606d1b2bfba9ba9e5386fabb7",
        locality: "Karapakkam",
        areaName: "Thoraipakkam",
        costForTwo: "₹350 for two",
        cuisines: ["Pizzas"],
        avgRating: 4.2,
        parentId: "721",
        avgRatingString: "4.2",
        totalRatingsString: "1K+",
        sla: {
          deliveryTime: 35,
          lastMileTravel: 6.4,
          serviceability: "SERVICEABLE",
          slaString: "30-35 mins",
          lastMileTravelString: "6.4 km",
          iconType: "ICON_TYPE_EMPTY",
        },
      },
    },
    {
      info: {
        id: "690703",
        name: "Pizza Hut",
        cloudinaryImageId: "2b4f62d606d1b2bfba9ba9e5386fabb7",
        locality: "Karapakkam",
        areaName: "Thoraipakkam",
        costForTwo: "₹350 for two",
        cuisines: ["Pizzas"],
        avgRating: 3.9,
        parentId: "721",
        avgRatingString: "4.2",
        totalRatingsString: "1K+",
        sla: {
          deliveryTime: 35,
          lastMileTravel: 6.4,
          serviceability: "SERVICEABLE",
          slaString: "30-35 mins",
          lastMileTravelString: "6.4 km",
          iconType: "ICON_TYPE_EMPTY",
        },
      },
    },
    {
      info: {
        id: "690704",
        name: "Pizza Hut",
        cloudinaryImageId: "2b4f62d606d1b2bfba9ba9e5386fabb7",
        locality: "Karapakkam",
        areaName: "Thoraipakkam",
        costForTwo: "₹350 for two",
        cuisines: ["Pizzas"],
        avgRating: 1.2,
        parentId: "721",
        avgRatingString: "4.2",
        totalRatingsString: "1K+",
        sla: {
          deliveryTime: 35,
          lastMileTravel: 6.4,
          serviceability: "SERVICEABLE",
          slaString: "30-35 mins",
          lastMileTravelString: "6.4 km",
          iconType: "ICON_TYPE_EMPTY",
        },
      },
    },
    {
      info: {
        id: "690705",
        name: "Pizza Hut",
        cloudinaryImageId: "2b4f62d606d1b2bfba9ba9e5386fabb7",
        locality: "Karapakkam",
        areaName: "Thoraipakkam",
        costForTwo: "₹350 for two",
        cuisines: ["Pizzas"],
        avgRating: 3.2,
        parentId: "721",
        avgRatingString: "4.2",
        totalRatingsString: "1K+",
        sla: {
          deliveryTime: 35,
          lastMileTravel: 6.4,
          serviceability: "SERVICEABLE",
          slaString: "30-35 mins",
          lastMileTravelString: "6.4 km",
          iconType: "ICON_TYPE_EMPTY",
        },
      },
    },
    {
      info: {
        id: "690706",
        name: "Pizza Hut",
        cloudinaryImageId: "2b4f62d606d1b2bfba9ba9e5386fabb7",
        locality: "Karapakkam",
        areaName: "Thoraipakkam",
        costForTwo: "₹350 for two",
        cuisines: ["Pizzas"],
        avgRating: 2.2,
        parentId: "721",
        avgRatingString: "4.2",
        totalRatingsString: "1K+",
        sla: {
          deliveryTime: 35,
          lastMileTravel: 6.4,
          serviceability: "SERVICEABLE",
          slaString: "30-35 mins",
          lastMileTravelString: "6.4 km",
          iconType: "ICON_TYPE_EMPTY",
        },
      },
    },
    {
      info: {
        id: "690707",
        name: "Pizza Hut",
        cloudinaryImageId: "2b4f62d606d1b2bfba9ba9e5386fabb7",
        locality: "Karapakkam",
        areaName: "Thoraipakkam",
        costForTwo: "₹350 for two",
        cuisines: ["Pizzas"],
        avgRating: 2.2,
        parentId: "721",
        avgRatingString: "4.2",
        totalRatingsString: "1K+",
        sla: {
          deliveryTime: 35,
          lastMileTravel: 6.4,
          serviceability: "SERVICEABLE",
          slaString: "30-35 mins",
          lastMileTravelString: "6.4 km",
          iconType: "ICON_TYPE_EMPTY",
        },
      },
    },
    {
      info: {
        id: "690708",
        name: "Pizza Hut",
        cloudinaryImageId: "2b4f62d606d1b2bfba9ba9e5386fabb7",
        locality: "Karapakkam",
        areaName: "Thoraipakkam",
        costForTwo: "₹350 for two",
        cuisines: ["Pizzas"],
        avgRating: 3.9,
        parentId: "721",
        avgRatingString: "4.2",
        totalRatingsString: "1K+",
        sla: {
          deliveryTime: 35,
          lastMileTravel: 6.4,
          serviceability: "SERVICEABLE",
          slaString: "30-35 mins",
          lastMileTravelString: "6.4 km",
          iconType: "ICON_TYPE_EMPTY",
        },
      },
    },
    {
      info: {
        id: "690709",
        name: "Pizza Hut",
        cloudinaryImageId: "2b4f62d606d1b2bfba9ba9e5386fabb7",
        locality: "Karapakkam",
        areaName: "Thoraipakkam",
        costForTwo: "₹350 for two",
        cuisines: ["Pizzas"],
        avgRating: 4.8,
        parentId: "721",
        avgRatingString: "4.2",
        totalRatingsString: "1K+",
        sla: {
          deliveryTime: 35,
          lastMileTravel: 6.4,
          serviceability: "SERVICEABLE",
          slaString: "30-35 mins",
          lastMileTravelString: "6.4 km",
          iconType: "ICON_TYPE_EMPTY",
        },
      },
    },
    {
      info: {
        id: "690710",
        name: "Pizza Hut",
        cloudinaryImageId: "2b4f62d606d1b2bfba9ba9e5386fabb7",
        locality: "Karapakkam",
        areaName: "Thoraipakkam",
        costForTwo: "₹350 for two",
        cuisines: ["Pizzas"],
        avgRating: 2.9,
        parentId: "721",
        avgRatingString: "4.2",
        totalRatingsString: "1K+",
        sla: {
          deliveryTime: 35,
          lastMileTravel: 6.4,
          serviceability: "SERVICEABLE",
          slaString: "30-35 mins",
          lastMileTravelString: "6.4 km",
          iconType: "ICON_TYPE_EMPTY",
        },
      },
    },
    {
      info: {
        id: "690711",
        name: "Pizza Hut",
        cloudinaryImageId: "2b4f62d606d1b2bfba9ba9e5386fabb7",
        locality: "Karapakkam",
        areaName: "Thoraipakkam",
        costForTwo: "₹350 for two",
        cuisines: ["Pizzas"],
        avgRating: 3.2,
        parentId: "721",
        avgRatingString: "4.2",
        totalRatingsString: "1K+",
        sla: {
          deliveryTime: 35,
          lastMileTravel: 6.4,
          serviceability: "SERVICEABLE",
          slaString: "30-35 mins",
          lastMileTravelString: "6.4 km",
          iconType: "ICON_TYPE_EMPTY",
        },
      },
    },
    {
      info: {
        id: "690712",
        name: "Pizza Hut",
        cloudinaryImageId: "2b4f62d606d1b2bfba9ba9e5386fabb7",
        locality: "Karapakkam",
        areaName: "Thoraipakkam",
        costForTwo: "₹350 for two",
        cuisines: ["Pizzas"],
        avgRating: 4.2,
        parentId: "721",
        avgRatingString: "4.2",
        totalRatingsString: "1K+",
        sla: {
          deliveryTime: 35,
          lastMileTravel: 6.4,
          serviceability: "SERVICEABLE",
          slaString: "30-35 mins",
          lastMileTravelString: "6.4 km",
          iconType: "ICON_TYPE_EMPTY",
        },
      },
    },
  ];